"""raw layer: 13 raw_* tables

Revision ID: 522a62ee5802
Revises: 
Create Date: 2026-07-01 07:31:02.248960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '522a62ee5802'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Text(), nullable=True),
    sa.Column('deal_id', sa.Text(), nullable=True),
    sa.Column('activity_type', sa.Text(), nullable=True),
    sa.Column('direction', sa.Text(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('responsible_user_id', sa.Text(), nullable=True),
    sa.Column('completed', sa.Text(), nullable=True),
    sa.Column('deadline_at', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('inn', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_deal_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Text(), nullable=True),
    sa.Column('unit_price', sa.Text(), nullable=True),
    sa.Column('discount', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.Text(), nullable=True),
    sa.Column('manager_id', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('contact_id', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('expected_amount', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.Text(), nullable=True),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('custom_deadline', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_marketing_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_date', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('campaign', sa.Text(), nullable=True),
    sa.Column('cost_amount', sa.Text(), nullable=True),
    sa.Column('currency', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Text(), nullable=True),
    sa.Column('deal_id', sa.Text(), nullable=True),
    sa.Column('payment_date', sa.Text(), nullable=True),
    sa.Column('amount', sa.Text(), nullable=True),
    sa.Column('payment_type', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_pipeline_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Text(), nullable=True),
    sa.Column('stage_id', sa.Text(), nullable=True),
    sa.Column('stage_name', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Text(), nullable=True),
    sa.Column('is_final', sa.Text(), nullable=True),
    sa.Column('is_success', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_production_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Text(), nullable=True),
    sa.Column('deal_id', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=True),
    sa.Column('planned_finish_at', sa.Text(), nullable=True),
    sa.Column('actual_finish_at', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('workshop', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Text(), nullable=True),
    sa.Column('sku', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('cost_price', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Text(), nullable=True),
    sa.Column('deal_id', sa.Text(), nullable=True),
    sa.Column('planned_date', sa.Text(), nullable=True),
    sa.Column('actual_date', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_stage_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Text(), nullable=True),
    sa.Column('deal_id', sa.Text(), nullable=True),
    sa.Column('old_stage_id', sa.Text(), nullable=True),
    sa.Column('new_stage_id', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('active', sa.Text(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_users')
    op.drop_table('raw_stage_history')
    op.drop_table('raw_shipments')
    op.drop_table('raw_products')
    op.drop_table('raw_production_orders')
    op.drop_table('raw_pipeline_stages')
    op.drop_table('raw_payments')
    op.drop_table('raw_marketing_costs')
    op.drop_table('raw_deals')
    op.drop_table('raw_deal_products')
    op.drop_table('raw_contacts')
    op.drop_table('raw_companies')
    op.drop_table('raw_activities')
    # ### end Alembic commands ###
