"""core layer: 15 typed tables (PK/FK/CHECK) + sources + data_quality_issues

Revision ID: 69c662503046
Revises: 522a62ee5802
Create Date: 2026-07-01 08:11:02.110089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69c662503046'
down_revision: Union[str, None] = '522a62ee5802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('inn', sa.String(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('data_quality_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('issue_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action in ('fixed','quarantined','flagged')", name='ck_dqi_action'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_stages',
    sa.Column('stage_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=True),
    sa.Column('stage_name', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('stage_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('cost_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('canonical_id', sa.String(), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('department', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('contacts',
    sa.Column('contact_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_table('marketing_costs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cost_date', sa.Date(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('campaign', sa.Text(), nullable=True),
    sa.Column('cost_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), server_default='RUB', nullable=False),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('custom_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_id', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('company_id', sa.String(), nullable=True),
    sa.Column('contact_id', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(), server_default='RUB', nullable=False),
    sa.Column('lost_reason', sa.Text(), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.contact_id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['pipeline_stages.stage_id'], ),
    sa.PrimaryKeyConstraint('deal_id')
    )
    op.create_table('activities',
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=True),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('responsible_user_id', sa.String(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("activity_type in ('call','email','task')", name='ck_activity_type'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.ForeignKeyConstraint(['responsible_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('activity_id')
    )
    op.create_table('deal_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("payment_type in ('prepayment','full','correction','unknown')", name='ck_payment_type'),
    sa.CheckConstraint("status in ('paid','pending')", name='ck_payment_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('production_orders',
    sa.Column('production_order_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('planned_finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('workshop', sa.Text(), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("status in ('planned','in_progress','done')", name='ck_production_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('production_order_id')
    )
    op.create_table('shipments',
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('actual_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("status in ('planned','shipped')", name='ck_shipment_status'),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.PrimaryKeyConstraint('shipment_id')
    )
    op.create_table('stage_history',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('deal_id', sa.String(), nullable=False),
    sa.Column('old_stage_id', sa.String(), nullable=True),
    sa.Column('new_stage_id', sa.String(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_by_id', sa.String(), nullable=True),
    sa.Column('has_quality_issue', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.deal_id'], ),
    sa.ForeignKeyConstraint(['new_stage_id'], ['pipeline_stages.stage_id'], ),
    sa.ForeignKeyConstraint(['old_stage_id'], ['pipeline_stages.stage_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    # ### end Alembic commands ###

    # Сид справочника `sources` — канонический набор каналов (нижний регистр).
    # Проверено по данным: deals.source/marketing_costs.source после нормализации
    # (Avito/avito/AVITO/Авито → avito, Website/website → website).
    sources = sa.table(
        "sources",
        sa.column("code", sa.String),
        sa.column("name", sa.String),
    )
    op.bulk_insert(
        sources,
        [
            {"code": "avito", "name": "Avito"},
            {"code": "website", "name": "Сайт"},
            {"code": "yandex_direct", "name": "Яндекс.Директ"},
            {"code": "phone", "name": "Телефон"},
            {"code": "referral", "name": "Рекомендации"},
            {"code": "telegram", "name": "Telegram"},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage_history')
    op.drop_table('shipments')
    op.drop_table('production_orders')
    op.drop_table('payments')
    op.drop_table('deal_products')
    op.drop_table('activities')
    op.drop_table('deals')
    op.drop_table('marketing_costs')
    op.drop_table('contacts')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('products')
    op.drop_table('pipeline_stages')
    op.drop_table('data_quality_issues')
    op.drop_table('companies')
    # ### end Alembic commands ###
